### ISSUE TITLE
Request parameters for distillation on imagesWoof and ImageSquawk datasets

### ISSUE THREAD

**Issue by lan41981** [DataDistillation/DataDAM#11]
Thanks for your Exciting work！
I encountered a problem where I desperately needed the parameters for distillation on the imagesWoof and ImageSquawk datasets. I tried many times myself, but couldn't achieve the corresponding results. Even the difference was very large. The more iterations of distillation, the worse it was.
Thank you for your efforts.

**Comment by DataDistillation** [comment]
Thank you for your interest in our work, We are sorry to hear you had some issues. Please find our distilled datasets for ImageWoof and Squack here: https://huggingface.co/datasets/uoft-dsp-lab/DataDAM. We also include the frozen model parameters which can be directly tested using our "distill_test_model.py" file in the main repo.
