### ISSUE TITLE
Hi,I done a ablation exp ,found your SAM module is useless,how to expain that?

### ISSUE THREAD

**Issue by Luo-Zhongwei** [DataDistillation/DataDAM#12]

**Comment by DataDistillation** [comment]
Hello, we unfortunately cannot respond to messages like this. We hope you will follow common etiquette for formal information requests. We would like to direct you to our methods ablations in the main paper. Additionally, we have uploaded the frozen models and the relevant datasets (https://huggingface.co/datasets/uoft-dsp-lab/DataDAM). They are also directly linked to our README.md. We hope this helps resolve your concerns. We will be closing this issue now. If you have specific questions, please maintain respectable online etiquette.
