### ISSUE TITLE
Request for ConvNet-3 Checkpoints (pth files) on CIFAR10 and CIFAR100 Datasets

### ISSUE THREAD

**Issue by Junjie31** [DataDistillation/DataDAM#5]
I hope this message finds you well. I am writing to kindly request the checkpoints (pth files) for ConvNet-3 on the CIFAR10, CIFAR100, and SVHN datasets. Or can you provide a related link?

I would like to inquire about the checkpoints for the Whole Dataset. Thank you very much!

I appreciate your time and assistance in this matter.

**Comment by DataDistillation** [comment]
Thank you for your interest and patience. We are in the process of releasing the checkpoints and datasets. They should be up in the coming week.

**Comment by shim94kr** [comment]
any update on this? I'm also waiting the release for other datasets also. Thank you for your effort!

**Comment by DataDistillation** [comment]
Hello, Thank you for your interest in our work. We are securing an accessible online platform to upload our saved images. We will reply in the thread once it is completed.

**Comment by DataDistillation** [comment]
Hello, we have updated the links on our README.md page to point to our uploaded synthetic datasets and model parameters. They are available via the HuggingFace Page here: (https://huggingface.co/datasets/uoft-dsp-lab/DataDAM). We have additionally included a new file, “distill_test_model.py” which will allow you to directly load the frozen models and evaluate them.
