### ISSUE TITLE
Access to Synthetic Data

### ISSUE THREAD

**Issue by paganpasta** [DataDistillation/DataDAM#7]
Hi,

Thanks for the code for your amazing work. 

It seems that the links to down the syn dataset are not functional. Would it be possible to provide an alternative to access those images? Also, would it be possible to share images for other datasets and IPCs as well? 

Thanks.

**Comment by DataDistillation** [comment]
Hello, Thank you for your interest in our work. We are securing an accessible online platform to upload our saved images. We will reply in the thread once it is completed.

**Comment by Luo-Zhongwei** [comment]
> Hello, Thank you for your interest in our work. We are securing an accessible online platform to upload our saved images. We will reply in the thread once it is completed.

hi,how things going? looking forward to your reply

**Comment by DataDistillation** [comment]
Hello, we have updated the links on our README.md page to point to our uploaded synthetic datasets and model parameters. They are available via the HuggingFace Page here: (https://huggingface.co/datasets/uoft-dsp-lab/DataDAM). We have additionally included a new file, “distill_test_model.py” which will allow you to directly load the frozen models and evaluate them.
