### ISSUE TITLE
Reproduction issue to the code

### ISSUE THREAD

**Issue by gihyunkim** [DataDistillation/DataDAM#8]
Hi, I am very interested in dataset condensation and your paper. I have tried to reproduce the performance of your code, however, I found that the code has weird point on "get_network" function. 

You set network setting from "get_default_convnet_setting" function but fix net_norm as "batch_norm" for ConvNet for some reason.

I ran the code with "instance_norm" as DM and couldn't get high performance (about 63%) as your paper.

I'd appreciate if you explain this situation and what is my problem for reproduction. 

Thank you.

**Comment by DataDistillation** [comment]
Hello, Thank you for your interest in our work. As in the code, please use batch-based normalization as it provides stable results.
